"""FELN as a short sequence of catalog choices, and the SQL it renders to.

A query is written as pieces, each one choice from a closed set built from the OKF catalog
and the request's own literal spans:

     Wells [water] where water depth <= 71.0; farther than 1000 meters from Pipelines [gas]
     ^ head: layer [subtype]  ^ condition        ^ head: relation + related layer [subtype]  .

``decompose`` turns a gold FELN into decisions (training targets, oracle) by searching the
same space ``render_*`` produces; ``pieces`` writes decisions as text; ``compose`` renders
decisions as FELN, so no SQL is ever generated by the model.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from itertools import combinations

from feln import FELN, parse_relation
from feln.identical import identical
from feln.units import to_meters

from .okf import Catalog, Column, Layer

RELATIONS = {  # FELN kind -> how a head piece says it ("{}" = distance span)
    "intersects": "intersecting",
    "contains": "containing",
    "within": "inside",
    "withinDistance": "within {} of",
    "notWithinDistance": "farther than {} from",
}
DISTANCE = ("withinDistance", "notWithinDistance")
MAX_LAYERS = 3
UNITS = {
    "kilometers": "kilometers", "kilometer": "kilometers", "kilometres": "kilometers",
    "kilometre": "kilometers", "km": "kilometers", "meters": "meters", "meter": "meters",
    "metres": "meters", "metre": "meters", "m": "meters", "miles": "miles", "mile": "miles",
    "mi": "miles", "feet": "feet", "foot": "feet", "ft": "feet",
}  # fmt: skip
NONE = "none"
ANY = "any"

_NUM = r"\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?"
_UNIT = "|".join(sorted(UNITS, key=len, reverse=True))
_DIST_RE = re.compile(rf"(?<![\w.])({_NUM})\s*-?\s*({_UNIT})\b", re.I)
_NUM_RE = re.compile(rf"(?<![\w.])-?(?:{_NUM})(?![\w])")
_QUOTE_RE = re.compile(r"(?<!\w)'([^'\n]*?)'(?!\w)|(?<!\w)\"([^\"\n]*?)\"(?!\w)")


# --------------------------------------------------------------------------- spans
@dataclass(frozen=True)
class Span:
    kind: str  # str | num | dist
    text: str  # literal as it will be rendered (quotes stripped, commas removed)
    start: int
    unit: str = ""  # dist only, canonical plural

    @property
    def label(self) -> str:
        return f"{self.text} {self.unit}" if self.kind == "dist" else self.text

    @property
    def year(self) -> bool:
        return self.kind == "num" and re.fullmatch(r"(19|20)\d\d", self.text) is not None


def normalize(text: str) -> str:
    return text.replace("‘", "'").replace("’", "'").replace("“", '"').replace("”", '"')


def spans(text: str) -> list[Span]:
    """Quoted strings, distances (number + unit) and bare numbers, in text order."""
    text = normalize(text)
    out: list[Span] = []
    masked = list(text)
    for m in _QUOTE_RE.finditer(text):
        g = 1 if m.group(1) is not None else 2
        out.append(Span("str", m.group(g), m.start(g)))
        masked[m.start() : m.end()] = " " * (m.end() - m.start())
    rest = "".join(masked)
    for m in _DIST_RE.finditer(rest):
        out.append(Span("dist", m.group(1).replace(",", ""), m.start(), UNITS[m.group(2).lower()]))
        masked[m.start() : m.end()] = " " * (m.end() - m.start())
    rest = "".join(masked)
    for m in _NUM_RE.finditer(rest):
        out.append(Span("num", m.group(0).replace(",", ""), m.start()))
    return sorted(out, key=lambda s: s.start)


def sample_spans(text: str, col: Column) -> list[Span]:
    """Unquoted mentions of the column's catalog sample values (case-insensitive)."""
    low = normalize(text).lower()
    found = []
    for v in col.samples:
        if len(v) < 2:
            continue
        m = re.search(rf"(?<!\w){re.escape(v.lower())}(?!\w)", low)
        if m:
            found.append(Span("str", v, m.start()))
    return found


# --------------------------------------------------------------------------- options
@dataclass(frozen=True)
class Option:
    key: str  # column|op, or "none"
    col: str
    op: str
    needs: str  # "", str, str2, num, num2, year, year2
    text: str  # how a condition piece says it; {0} and {1} stand for its literal(s)


def _options(col: Column) -> list[Option]:
    a, c, k = col.alias, col.name, col.kind

    def o(op, needs, text):
        return Option(f"{c}|{op}", c, op, needs, text)

    blank = [o("blank", "", f"{a} is blank"), o("notblank", "", f"{a} is not blank")]
    if k == "like":
        return [
            o("contains", "str", f"{a} contains {{0}}"),
            o("starts", "str", f"{a} starts with {{0}}"),
            o("ends", "str", f"{a} ends with {{0}}"),
            *blank,
        ]
    if k in ("upper", "text"):
        return [
            o("is", "str", f"{a} is {{0}}"),
            o("isnot", "str", f"{a} is not {{0}}"),
            o("either", "str2", f"{a} is {{0}} or {{1}}"),
            *blank,
        ]
    if k == "yesno":
        return [o(f"{op}:{v}", "", f"{a} is {'not ' if op == 'isnot' else ''}{v.lower()}")
                for op in ("is", "isnot") for v in ("YES", "NO")] + blank  # fmt: skip
    if k == "code":
        labels = {**{s: s for s in col.samples}, **col.domain}
        return [o(f"{op}:{code}", "", f"{a} is {'not ' if op == 'isnot' else ''}{label}")
                for op in ("is", "isnot") for code, label in labels.items()]  # fmt: skip
    if k == "flag":
        return [o("is:1", "", f"{a} is yes"), o("is:0", "", f"{a} is no")]
    if k == "number":
        return [
            o("eq", "num", f"{a} = {{0}}"),
            o("lt", "num", f"{a} < {{0}}"),
            o("gt", "num", f"{a} > {{0}}"),
            o("le", "num", f"{a} <= {{0}}"),
            o("ge", "num", f"{a} >= {{0}}"),
            o("between", "num2", f"{a} between {{0}} and {{1}}"),
        ]
    if k == "date":
        return [
            o("after", "year", f"{a} after {{0}}"),
            o("since", "year", f"{a} since {{0}}"),
            o("before", "year", f"{a} before {{0}}"),
            o("through", "year", f"{a} through {{0}}"),
            o("in", "year", f"{a} in {{0}}"),
            o("between", "year2", f"{a} between {{0}} and {{1}}"),
        ]
    return []


def options(layer: Layer) -> dict[str, Option]:
    out = {NONE: Option(NONE, "", NONE, "", "")}
    for col in layer.columns.values():
        out.update((opt.key, opt) for opt in _options(col))
    return out


def values(opt: Option, col: Column | None, found: list[Span], text: str) -> list[tuple[str, ...]]:
    """Literal tuples the request offers for this option, in text order, deduplicated."""
    if not opt.needs:
        return [()]
    if opt.needs.startswith("str"):
        pool = [s for s in found if s.kind == "str" and s.text]
        if col is not None and col.kind != "like":
            seen = {s.text.upper() for s in pool}
            pool += [s for s in sample_spans(text, col) if s.text.upper() not in seen]
            pool.sort(key=lambda s: s.start)
    elif opt.needs.startswith("year"):
        pool = [s for s in found if s.year]
    else:  # a measured value may carry a unit ("68.0 meters"), so distances qualify too
        pool = [s for s in found if s.kind in ("num", "dist")]
    texts = list(dict.fromkeys(s.text for s in pool))
    if opt.needs.endswith("2"):
        return [(a, b) for a, b in combinations(texts, 2)]
    return [(t,) for t in texts]


def _q(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def render_condition(opt: Option, col: Column, vals: tuple[str, ...]) -> str:
    c, op = col.name, opt.op
    if col.kind == "upper":
        vals = tuple(v.upper() for v in vals)
    if op in ("blank", "notblank"):
        return f"{c} {'=' if op == 'blank' else '<>'} ''"
    if col.kind == "like":
        v = vals[0]
        pattern = {"contains": f"%{v}%", "starts": f"{v}%", "ends": f"%{v}"}[op]
        return f"{c} LIKE {_q(pattern)}"
    if col.kind in ("upper", "text"):
        if op == "either":
            return f"{c} = {_q(vals[0])} or {c} = {_q(vals[1])}"
        return f"{c} {'=' if op == 'is' else '<>'} {_q(vals[0])}"
    if col.kind in ("yesno", "code"):
        which, code = op.split(":", 1)
        return f"{c} {'=' if which == 'is' else '<>'} {_q(code)}"
    if col.kind == "flag":
        return f"{c} = cast({op.split(':')[1]} as {col.cast})"
    if col.kind == "number":
        if op == "between":
            return f"{c} BETWEEN cast({vals[0]} as {col.cast}) AND cast({vals[1]} as {col.cast})"
        sym = {"eq": "=", "lt": "<", "gt": ">", "le": "<=", "ge": ">="}[op]
        return f"{c} {sym} cast({vals[0]} as {col.cast})"
    if col.kind == "date":
        y = [int(v) for v in vals]
        ts = lambda year: f"timestamp '{year}-01-01'"  # noqa: E731
        lo, hi = {
            "after": (y[0] + 1, None), "since": (y[0], None), "before": (None, y[0]),
            "through": (None, y[0] + 1), "in": (y[0], y[0] + 1),
            "between": (y[0], y[-1] + 1),
        }[op]  # fmt: skip
        parts = ([f"{c} >= {ts(lo)}"] if lo else []) + ([f"{c} < {ts(hi)}"] if hi else [])
        return " AND ".join(parts)
    raise ValueError(f"cannot render {opt.key}")


def render_where(layer: Layer, code: str, opt: Option, vals: tuple[str, ...]) -> str:
    sub = ""
    if code != ANY:
        st = layer.columns[layer.subtype]
        sub = f"{st.name} = cast({code} as {st.cast})"
    cond = "" if opt.key == NONE else render_condition(opt, layer.columns[opt.col], vals)
    if sub and cond:
        return f"{sub} and ({cond})"
    return sub or cond


# --------------------------------------------------------------------------- decisions
@dataclass
class Decisions:
    primary: str
    secondaries: tuple[str, ...]
    subtype: dict[str, str] = field(default_factory=dict)
    condition: dict[str, str] = field(default_factory=dict)
    value: dict[str, tuple[str, ...]] = field(default_factory=dict)
    relation: dict[str, str] = field(default_factory=dict)
    distance: dict[str, str] = field(default_factory=dict)  # span label, e.g. "25 kilometers"

    @property
    def layers(self) -> list[str]:
        return [self.primary, *self.secondaries]


def compose(cat: Catalog, d: Decisions) -> dict:
    """Decisions -> FELN meta (layers / where / relations)."""
    where = []
    for name in d.layers:
        ly = cat[name]
        opt = options(ly)[d.condition.get(name, NONE)]
        where.append(render_where(ly, d.subtype.get(name, ANY), opt, d.value.get(name, ())))
    rels = []
    for name in d.secondaries:
        kind = d.relation[name]
        rels.append(f"{kind} {d.distance[name]}" if kind in DISTANCE else kind)
    return {"layers": d.layers, "where": where, "relations": rels}


def _same_cond(a: str, b: str) -> bool:
    a, b = a.replace(" ILIKE ", " LIKE "), b.replace(" ILIKE ", " LIKE ")
    return a == b or identical(a, b)


def _split_where(ly: Layer, where: str) -> tuple[str, str]:
    st = ly.columns[ly.subtype]
    m = re.match(rf"^{re.escape(st.name)} = cast\((-?\d+) as [\w ]+?\)(.*)$", where.strip(), re.I)
    if not m:
        return ANY, where.strip()
    rest = m.group(2).strip()
    if rest.lower().startswith("and (") and rest.endswith(")"):
        return m.group(1), rest[5:-1]
    if rest:
        raise ValueError(f"unexpected where tail: {rest!r}")
    return m.group(1), ""


def decompose(cat: Catalog, text: str, meta: dict) -> Decisions:
    """Gold FELN -> decisions; raises ValueError when the grammar cannot reproduce it."""
    names = meta["layers"]
    if not 1 <= len(names) <= MAX_LAYERS or len(set(names)) != len(names):
        raise ValueError(f"layers: {len(names)} layers, at most {MAX_LAYERS} distinct")
    d = Decisions(names[0], tuple(names[1:]))  # gold order: the text mostly follows it
    found = spans(text)
    for name, where in zip(names, meta["where"]):
        ly = cat[name]
        code, cond = _split_where(ly, where)
        d.subtype[name] = code
        if not cond:
            d.condition[name] = NONE
            continue
        m = re.match(r"\(?\s*(\w+)", cond)
        ident = m.group(1).lower() if m else ""
        hit = None
        for opt in options(ly).values():
            if opt.col.lower() != ident:
                continue
            col = ly.columns[opt.col]
            hit = next((v for v in values(opt, col, found, text)
                        if _same_cond(render_condition(opt, col, v), cond)), None)  # fmt: skip
            if hit is not None:
                d.condition[name], d.value[name] = opt.key, hit
                break
        if hit is None:
            raise ValueError(f"{name}: no option renders {cond!r}")
    dists = [s for s in found if s.kind == "dist"]
    for name, rel in zip(names[1:], meta["relations"]):
        r = parse_relation(rel)
        d.relation[name] = "within" if r.kind == "inside" else r.kind
        if r.kind in DISTANCE:
            want = to_meters(r.distance, r.unit)
            fits = [s for s in dists if abs(to_meters(float(s.text), s.unit) - want) < 0.01]
            fresh = [s for s in fits if s.label not in d.distance.values()]  # 1 km = 1000 m
            span = (fresh or fits or [None])[0]
            if span is None:
                raise ValueError(f"{name}: distance {rel!r} not in text")
            d.distance[name] = span.label
    return d


def same(a: dict, b: dict) -> bool:
    return FELN(**a).same(FELN(**b))


# --------------------------------------------------------------------------- target
END = "."


def subtype_label(cat: Catalog, layer: str, code: str) -> str:
    ly = cat[layer]
    return "" if code == ANY else ly.columns[ly.subtype].domain[code].lower()


def mentions(cat: Catalog, text: str) -> dict[str, int]:
    """How often each subtype label (any layer) is named in the request, longest match first."""
    labels = {
        lab.lower() for ly in cat.layers.values() for lab in ly.columns[ly.subtype].domain.values()
    }
    alts = [
        re.escape(lab).replace("shows", "shows?") for lab in sorted(labels, key=len, reverse=True)
    ]
    counts: dict[str, int] = {}
    for m in re.finditer(rf"(?<![\w/])({'|'.join(alts)})(?![\w/])", normalize(text).lower()):
        lab = m.group(1) if m.group(1) in labels else m.group(1) + "s"
        counts[lab] = counts.get(lab, 0) + 1
    return counts


def head(cat: Catalog, name: str, code: str, kind: str = "", dist: str = "") -> str:
    """' Wells [oil]' for the primary, '; within 5 kilometers of Pipelines [gas]' for a related layer."""
    sub = f"{name} [{subtype_label(cat, name, code) or ANY}]"
    return f"; {RELATIONS[kind].format(dist)} {sub}" if kind else f" {sub}"


def condition(opt: Option, vals: tuple[str, ...]) -> str:
    """' where water depth <= 71.0'"""
    lits = [v if opt.needs.startswith(("num", "year")) else f"'{v}'" for v in vals]
    return f" where {opt.text.format(*lits)}"


def heads(cat: Catalog, used: list[str], dists: list[str]) -> list[tuple[str, tuple]]:
    """Head pieces of the next layer: (piece, (layer, subtype code, relation, distance))."""
    rels = [("", "")]
    if used:
        rels = [(k, "") for k in RELATIONS if k not in DISTANCE]
        rels += [(k, d) for k in DISTANCE for d in dists]
    return [
        (head(cat, name, code, k, d), (name, code, k, d))
        for name, ly in cat.layers.items()
        if name not in used
        for code in [*ly.columns[ly.subtype].domain, ANY]
        for k, d in rels
    ]


def conditions(cat: Catalog, name: str, found: list[Span], text: str) -> list[tuple[str, tuple]]:
    """Condition pieces of a layer: (piece, (option key, literals))."""
    ly = cat[name]
    return [
        (condition(opt, vals), (opt.key, vals))
        for opt in options(ly).values()
        if opt.key != NONE
        for vals in values(opt, ly.columns[opt.col], found, text)
    ]


def pieces(cat: Catalog, d: Decisions) -> list[str]:
    """Decisions as the model writes them, one piece per choice, ending in END."""
    out = []
    for name in d.layers:
        rel = d.relation.get(name, "")
        out.append(head(cat, name, d.subtype[name], rel, d.distance.get(name, "")))
        if d.condition[name] != NONE:
            out.append(condition(options(cat[name])[d.condition[name]], d.value[name]))
    return out + [END]


def hints(cat: Catalog, index: dict[str, dict[str, set[str]]], found: list[Span]) -> str:
    """Where each quoted literal occurs in the project data: "'GASSCO AS' = Pipelines current
    operator". ``index`` holds the lower-cased distinct values of each text column."""
    out = []
    for v in dict.fromkeys(s.text for s in found if s.kind == "str" and s.text):
        low = v.lower()
        hits = [
            f"{name} {ly.columns[c].alias}"
            for name, ly in cat.layers.items()
            for c, vals in index.get(name, {}).items()
            if (any(low in x for x in vals) if ly.columns[c].kind == "like" else low in vals)
        ]
        out.append(f"'{v}' = {', '.join(hits) or 'no match'}")
    return "; ".join(out)


def prompt(text: str, hint: str) -> str:
    return f"Request: {text}\n" + (f"Values: {hint}\n" if hint else "") + "FELN:"


def tags(cat: Catalog, text: str, d: Decisions) -> list[str]:
    """``implicit``: a gold layer is never named (only through a subtype word or a column).
    ``noisy``: the gold contradicts the text: a layer the text names is missing, or a gold
    subtype is never said."""
    low, named = normalize(text).lower(), mentions(cat, text)
    out = []
    if any(
        not re.search(rf"\b{re.escape(re.sub('(ies|s)$', '', n.lower()))}", low) for n in d.layers
    ):
        out.append("implicit")
    if any(
        re.search(rf"\b{re.escape(ly.noun)}\b", low)
        for n, ly in cat.layers.items()
        if n not in d.layers
    ) or any(
        subtype_label(cat, n, d.subtype[n]) not in named for n in d.layers if d.subtype[n] != ANY
    ):
        out.append("noisy")
    return out
